### ISSUE TITLE
Focal point mousewheel zooming doesnt work in Firefox

### ISSUE THREAD

**Issue by gavJackson** [timmywil/panzoom#28]
I have tried the mousewheel focal point zooming demo (http://timmywil.github.io/jquery.panzoom/demo/) in FF on a mac and PC and it doesn't work in either.  Looks like the mousewheel.focal event isnt being triggered/picked up

**Comment by viion** [comment]
Hello

Sorry to touch such an old topic. The latest version doesn't seem to work in Firefox without this plugin. I did not know this until I found this issue. I only found this issue because of a commit on `.bowerrc` was the only commit in the past 3 years which references the problem.

Would it be useful to add to the FAQ that https://github.com/jquery/jquery-mousewheel is required for this to work in Firefox? (Or am I being totally blind?)

Codepen example: http://codepen.io/viion/pen/eBaVzN
