### ISSUE TITLE
Wildly veering on mousewheel zoom with animate: true

### ISSUE THREAD

**Issue by KensingtonTech** [timmywil/panzoom#331]
Dear Sir,

When using mousewheel zoom with animate: true, the the element goes veering wildly off to the right and out of the frame, when zooming out.  Zooming sort of works, but appears to be heading off to the right of the focal point as well.  With animate: false, it zooms to the correct focal point.

Any help you can offer would be greatly appreciated.

jquery.panzoom = 3.2.2
jquery = 3.2.1
jquery-mousewheel = 3.1.13

Code which produces the problem, taken from the focal section of your demo page.  All I've done is change animate: false to animate: true.

```
<!doctype html>
<html>
  <head>
    <title>Panzoom for jQuery</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <style type="text/css">
      body { background: #F5FCFF; color: #333666; }
      section { text-align: center; margin: 50px 0; }
      .panzoom-parent { border: 2px solid #333; }
      .panzoom-parent .panzoom { border: 2px dashed #666; }
      .buttons { margin: 40px 0 0; }
    </style>
    <script src="http://timmywil.github.io/jquery.panzoom/test/libs/jquery.js"></script>
    <script src="http://timmywil.github.io/jquery.panzoom/dist/jquery.panzoom.js"></script>
    <script src="http://timmywil.github.io/jquery.panzoom/test/libs/jquery.mousewheel.js"></script>
  </head>
  <body>
    <hr>
    <section id="focal">
      <h1>Use the mousewheel to zoom on a focal point</h1>
      <div class="parent">
        <div class="panzoom">
          <img src="http://blog.millermedeiros.com/wp-content/uploads/2010/04/awesome_tiger.svg" width="900" height="900">
        </div>
      </div>
      <script>
        (function() {
          var $section = $('#focal');
          var $panzoom = $section.find('.panzoom').panzoom();
          $panzoom.parent().on('mousewheel.focal', function( e ) {
            e.preventDefault();
            var delta = e.delta || e.originalEvent.wheelDelta;
            var zoomOut = delta ? delta < 0 : e.originalEvent.deltaY > 0;
            $panzoom.panzoom('zoom', zoomOut, {
              increment: 0.1,
              animate: true,
              focal: e
            });
          });
        })();
      </script>
    </section>

    <!-- Load livereload if not phantom or github -->
    <script>
      if ( !window.phantom && !/github/.test(window.location.hostname) ) document.write('<scr' + 'ipt src="http://' + location.hostname + ':35711/livereload.js"></scr' + 'ipt>');
    </script>
  </body>
</html>
```

**Comment by borealissw** [comment]
Hi,

any advances with this?

I've determined the following after a spot of investigation.

Firstly, for anyone looking for a workaround, you need to explicitly set `animate: true` in the options as the `setMatrix `code will animate by default when an explicit scale isn't given.

Secondly, it's not browser specific. I've not done a lot of testing, but behaviour is identical on both Chrome 62 and Edge 41.

Finally, the issue is timing-related:
1. if the mouse wheel is given a single increment and then given a pause before moving the wheel further, the zooming acts correctly. Speed up the wheel use and the problem starts. 
2. changing the duration of the transition affects in the defaults this needed delay - set this to 5ms and you don't encounter the problem.

I've no idea of the details of why the drift should happen, but to me, it looks like a decent workaround would involve some form of guard at the start of `zoom` to ensure the browser is allowed to complete the (asynchronous) transition process before being requested to perform another zoom.

I'll submit a pull request if I have the time to write that workaround.
