### ISSUE TITLE
Image blurry after zoom in safari browser

### ISSUE THREAD

**Issue by akverma080** [timmywil/panzoom#343]
### Subject of the issue
Image blurry after click on zoom in button in safari browser. 

### Your environment
* version of 2.05
* version of jquery 1.10
* which browser and its version

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](http://jsbin.com/mofeli/edit?html,js,output) as a base.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by jtara** [comment]
What kind of image? Bitmap or SVG? I would expect a bitmap to be blurry if not higher resolution.

That said, I've experienced some blurring of SVG content in SOME situations, still trying to identify the exact scenario.

- When I zoom a div that wraps an SVG, there is no blurring.
- When I zoom a more complex layout, with a div that wraps an SVG, along with two more SVGs and a canvas that are positioned over the div, the first SVG is blurry when zoomed.

``` html
<div style='position:relative'>
  <svg> .... </svg>
  <canvas style='position:absolute'></canvas>
  <svg style='position:absolute'>...</svg>
  <svg style='position_absolute'>...</svg>
</div>
```
Note: I don't actually use inline styles as shown. It's applied with classes and a stylesheet. Just wanted to show what is positioned and how.

I could alternatively transform the overlaid images, rather than positioning them, but that wouldn't seem to solve the problem, as the problem is with the first (not-positioned) SVG.

I will try a work-around where I also position the first SVG. I will have to have some code set the dimensions of the container, then, as currently the container just gets it's size from content, which is the first SVG.

To be clear, with the above layout, the first SVG blurs on zoom. The others don't. There is expected blurring of the canvas. (As a compromise, the canvas has 2X the resolution of the device, and so the blur is acceptable at 4X.)

**Comment by jtara** [comment]
In my case, the blurring was partially solved with CSS `shape-rendering: crispEdges`. Another contributor to the blurring is that I use CSS to set the opacity of the image to < 1.0.

When using an SVG with opacity 1.0, there is no blur.

Again, I would **expect** blurring with any kind of bitmap image, e.g. .png, .gif, .jpg.

**Comment by SkyHolder** [comment]
i use transforms, its resolve it for me
```
$elem.on('panzoomzoom', function(e, panzoom, scale, opts) {
                setTimeout(function() {
                    if (is_true) {
                        $('.blueprints image').css('transform', 'translateZ(0)');
                        is_true = false;
                    } else{
                        $('.blueprints image').css('transform', 'translateZ(1px)');
                        is_true=true;
                    }
                 }, 550);
            });
```

550 its transition duration + 50 ms
