### ISSUE TITLE
panzoom can't work

### ISSUE THREAD

**Issue by SoHi1990** [timmywil/panzoom#406]
when i use panzoom in ios 12+ is perfect，but it's not work in ios 13+

ios 13.1.2

panzoom 3.2.3

safari

**Comment by timmywil** [comment]
Thanks for opening an issue. The library has been completely rewritten since 3.2.3 and the master branch should work fine in iOS 13. However, the release is not quite ready. Feel free to use the master branch or follow along in the [GitHub project](https://github.com/timmywil/panzoom/projects/1) to see when the new version is completed.
