### ISSUE TITLE
Panzoom not updating drag animation with canvas under Chrome

### ISSUE THREAD

**Issue by edzhelyov** [timmywil/panzoom#422]
### Subject of the issue

In this fiddle https://jsfiddle.net/xq5er6w4/ if you try to drag the container it transition property will update, but you won't see any animation. If you force a repaint it will be in the right position. This happens if you have a canvas.

In this fiddle https://jsfiddle.net/rf43ew67/ with a div, there are no issues.
Seems that it doesn't happen in Firefox.

Please advise, maybe I'm using panzoom incorrectly. This is the smallest reproducible example the actual production usage is more complex.

### Your environment

- 3.2.3
- Chrome 78, but happens on 77 and 70.

**Comment by timmywil** [comment]
Thanks for opening an issue. The jQuery plugin version of panzoom is no longer being maintained. I plan on making a jQuery plugin wrapper for the new version, which is now a universal library and does not depend on jQuery. The library has changed so much, I don't know if your issue is still present on the master branch.

That said, the code looks right, but I don't actually see an issue. The element containing the canvas drags around fine for me in Chrome or FF.

If you can reproduce in the new version, I'll gladly reopen.

**Comment by edzhelyov** [comment]
Hi, Thanks for responding so fast. I really like projects that strive to maintain a very low amount of open issues, but it feels a bit sad to have your issue closed so fast without having the ability to react.

I've provided the wrong gist in the first paragraph and it contained the div example, I'm sorry for that, I messed with fiddle somehow. Here is a correct link: https://jsfiddle.net/Lvru2p6d/
Can you test again and tell me what is the behavior on your side?

I have a few questions regarding the new version. You don't have an official release, is master save to use? How can I get a compiled version of master to try in my examples?

**Comment by timmywil** [comment]
> it feels a bit sad to have your issue closed so fast without having the ability to react

The purpose of closing is to indicate to me, the maintainer, that I don't know of anything more I can do. I keep a close eye on closed issues and they can always be reopened. It is not meant as an insult if your issue is closed quickly. It may very well be legitimate, but often I receive no response when asking for more info and I don't want to leave issues like that open. Also, your issue relates to the old jQuery plugin, which I honestly don't want to spend time maintaining anymore.

The master branch should be safe to use. When a release goes out, the built files will be included in the tags, but for now, the only way to get a compiled version is to clone the repo and run `yarn && yarn build` or `npm i && npm run build`.

As for the issue, I do see it now. I wonder if it's a Chrome bug because the transform seems to be getting set correctly on the div, but nothing is changing.

**Comment by edzhelyov** [comment]
I think it's indeed an issue in Chrome, as this happens after recent updates to 77 and 78.
I will figure out a specific workaround for our case or try the master version. Thanks.
