### ISSUE TITLE
Pinch zoom doesn't work in Chrome on Android

### ISSUE THREAD

**Issue by JPustkuchen** [timmywil/panzoom#429]
### Subject of the issue

Like described in #303 and 349 the pinch zoom doesn't work for us in Chrome on Android and on Windows 10 Touch. Firefox on Android works!

We're using the following settings:
```
$element.panzoom({
            $zoomIn: $mapControlsWrapper.find(".zoom-in"),
            $zoomOut: $mapControlsWrapper.find(".zoom-out"),
            $zoomRange: $mapControlsWrapper.find(".zoom-range"),
            $reset: $mapControlsWrapper.find(".reset"),
            step: 0.5,
            minScale: 1.0,
            maxScale: 5.0,
            panOnlyWhenZoomed: true,
            // Bugfix: With which (click) = 1 (default), this doesn't work
            // on Android Chrome with touch!
            // See https://github.com/timmywil/panzoom/issues/303 - but even the latest
            // 3.2.3 release does not work.
            which: -1,
            onChange: function( e, panzoom ){
                if(!_plugins_webks_teileskizzen_layer_isTouchDevice()){
                    // check if its a touch device - the on change event is fired to easy on those devices
                    plugins_webks_teileskizzen_layer_tooltip_hideAll();
                    // Allow click-zoom on non-touch devices:
                    panzoom.options.which = 1;
                }
            }
```
        });

We're using it here: https://www.quad-company.de/quad/ersatzteile/herkules-cectek/quadrift-500-efi-t5-t6-ab-bj-14/getriebeausgangswelle

Adding 
`  which: -1,`
like described in #303 fixes the problem as workaround.

We're using the latest version where this should have been fixed, I've got no idea, why it doesn't work.

### Your environment

- Version of panzoom: 3.2.3
- Browser and browser version: Chrome 78.0.3904.108 on Android 9

### Expected behaviour

Panning in via gesture leads to zoom

### Actual behaviour

Content jumps around or nothing happens on touch

### Steps to reproduce
See above

**Comment by timmywil** [comment]
Thanks for opening an issue. This library has since been completely rewritten and is no longer a jQuery plugin. The jQuery plugin itself is no longer being maintained. The new release will be ready as soon as I can finish some testing. When that's ready, I'm going to write a jQuery plugin wrapper so you won't have to change the API too much.

I believe this particular issue had to do with Chrome adding pointer event support, and the old jQuery plugin version wasn't built to support pinch gestures using pointer events. The new Panzoom does support that tho.

I'm sorry I don't have a quick solution for you. For now, you can update to the master branch and use the new API, or wait for the jQuery wrapper, which I plan on having ready in the next week or so.

**Comment by timmywil** [comment]
Oh, but I would like to point you to [this patch](https://github.com/timmywil/panzoom/pull/356) for the jQuery plugin. You could apply that if you need a fix right away.

**Comment by JPustkuchen** [comment]
Thank you very much, Timmy! :)

**Comment by JPustkuchen** [comment]
PS: I just tested the patch and it doesn't solve the problem properly. With which: -1 it still works a lot better. With just the patch the image jumps around sometimes on touch.

I'm very much looking forward to the new release!

I also had a look at https://github.com/anvaka/panzoom in this context and it's also working well, perhaps it would be interesting to point out differences or join the projects. HOWEVER: THANK YOU! :)
