### ISSUE TITLE
Add 'zoomWithWheel' to init options

### ISSUE THREAD

**Issue by UltraCakeBakery** [timmywil/panzoom#435]
### Subject of the issue

Right now I add zoom functionality like described in the docs.

```
const panzoom = PanZoom( canvasElement )
canvasWrapper.addEventListener( 'wheel', panzoom.zoomWithWheel )
```

### Expected behaviour

It would be nice to have the option to add it automatically.

```
const panzoom = PanZoom( this.$refs.canvasVisuals, { zoomWithWheel: true // or a reference to a element })


### Actual behaviour

It isn't a thing.

**Comment by timmywil** [comment]
Thanks for opening an issue. I'm hesitant to add this because it could lead to more options for other events. This is probably a common one, but so might be the click events binding `zoomIn` or `zoomOut`, and then that could lead to even more options for other events. That said, with a few +1s from other users, I'd be willing to do this.
