### ISSUE TITLE
cannot scroll on mobile

### ISSUE THREAD

**Issue by LittleHamster** [timmywil/panzoom#467]
### Describe the bug

when using panzoom, you cant scroll the page when inside the panzoon element. 

### Your environment

iOS - Safari

### Expected behavior

Should be able to scroll 

### Actual behavior
Cannot scroll

**Comment by timmywil** [comment]
Thanks for opening an issue. This is intentional behavior. This happens because Panzoom handles the pointer event in order to drag the element. There's isn't really a way around this because you can either scroll or drag, but not both. You can still scroll if you touch outside the panzoom container.
