### ISSUE TITLE
"Infinite canvas" — controlling child via parent container element

### ISSUE THREAD

**Issue by nwittwer** [timmywil/panzoom#472]
I have a similar question to one that was previously answered, but not sure how to achieve it with the new Panzoom (post-jQuery) which I'm very interested in using. It was previously answered here for the jQuery version: https://github.com/timmywil/panzoom/issues/39

How can I make both the container and the child element have the Panzoom attributes—zoomable, pannable, etc. using the new API in Panzoom? I'd like panning/zooming on the parent element to move the child. 

Example (Figma):
![Screen Recording 2020-04-05 at 6 17 52 PM](https://user-images.githubusercontent.com/6360459/78503971-64d2d980-776a-11ea-9c77-43fe24b25dc1.gif)

**Comment by timmywil** [comment]
I played around with this a bit in my demos. The old `$set` option wouldn't really be appropriate for the rewrite. I thought about using the `setTransform` option, but thought better of it because I think we can make something cleaner.

I was able to achieve this behavior by changing two lines in panzoom.ts, basically binding the down handler to the parent instead of the element. Everything else works with no further changes. So, I've added an option to the master branch called `canvas`. Please try it out before I release it to make sure this is accomplishing what you want.

```js
Panzoom(elem, { canvas: true })
```

**Comment by timmywil** [comment]
Oh, you can try it out with the following...

```bash
$ git clone git@github.com:timmywil/panzoom.git
$ cd panzoom
$ npm install
$ npm run build
```

panzoom.js will be in the `dist/` folder.

**Comment by nwittwer** [comment]
Yep, works exactly as imagined! Thanks @timmywil!

Demo (using the Panzoom from `dist/`) + Vue:
https://codesandbox.io/s/musing-tesla-pxwqe

See `src/components/PanzoomContainer.vue` for usage.

**Comment by timmywil** [comment]
Thanks for checking. Release in [4.1.0](https://github.com/timmywil/panzoom/commit/3ce5ee9f87a56f808c2e1d963a6ffc65fedfe138)
