### ISSUE TITLE
Panzoom is not defined

### ISSUE THREAD

**Issue by csandreas1** [timmywil/panzoom#478]
Hi,
I am including the script via a script tag from [cdnjs](https://cdnjs.com/libraries/jquery.panzoom).

However, when I call [Panzoom functions](https://timmywil.com/panzoom/demo/) I get "Panzoom is not defined" in the console.

The script is loaded on the page after jQuery v 3.2.1

 Have I done anything wrong?

**Comment by timmywil** [comment]
Thanks for opening an issue. It looks like you're using the old version of Panzoom, which is a jQuery plugin. The demo page you linked is using the new version that no longer depends on jQuery. I suggest either using the new version or you can find the docs for the old version here: https://github.com/timmywil/panzoom/tree/36f4f6fe2f17770bc73e79af18b3943b3c5faf9a

Just be advised that the old version will not be receiving any more patches.

**Comment by csandreas1** [comment]
@timmywil Okay I will go with the new version, can you give me a link on  hat panzoom.js file? I have searched and haven't found it.

**Comment by timmywil** [comment]
So far, I've only considered installing Panzoom with npm. It is not currently on any CDNs because it does not expose a global and is meant to be used as a module (using [babel](https://babeljs.io/), [browserify](http://browserify.org/), or [native import where supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

However, I would consider making Panzoom export a global if there was enough interest. I've made a new issue for voting [here](https://github.com/timmywil/panzoom/issues/480). Please add your upvote if you would prefer to use Panzoom from `window.Panzoom` instead of as a module.
