### ISSUE TITLE
Zoom and pan (with animate) methods zoom into the wrong point in contain mode

### ISSUE THREAD

**Issue by harebuus** [timmywil/panzoom#485]
### Describe the bug

Sorry, I don't understand how to use jsbin. So I wrote the example [here](https://codepen.io/harebuus/pen/JjYOdjX).

I am trying to zoom in to the point I want. I add focal to the zoom function, but it does not zoom to the point I want.
When the "contain" setting is "outside", zoom and pan (with animate) methods zoom into the wrong point when called consecutively.
The "pan" method looks glitchy when delayed by "setTimeOut".

### Your environment
panzoom: 4.1.0
Mozilla Firefox 75 (64 Bit)
Expected behavior

### Steps to reproduce
[https://codepen.io/harebuus/pen/JjYOdjX](https://codepen.io/harebuus/pen/JjYOdjX)

**Comment by bariskrdrl** [comment]
Is there any improvement about this, and I am having the same problem. @timmywil @harebuus

**Comment by timmywil** [comment]
The point is wrong because it needs to finish painting to get proper dimensions for containment. As you pointed out, the README suggests wrapping the second call in `setTimeout` to wait for the paint and get proper dimensions. However, if you're trying to animate the calls, that wouldn't work so well. What would work is if you knew the exact point ahead of time, but I'll have to think on this.

**Comment by bariskrdrl** [comment]
Thanks. I am following for this development.

**Comment by timmywil** [comment]
I was looking at this again. I'd like to avoid duplicating all the calculations the browser does for you. This is part of what keeps Panzoom so lightweight. It seems all you need is a zoom method that will zoom to the right spot. The `contain` option can have some side effects, but the `focal` option is expected to be translated to its post-zoom coordinates. So, I realized I already wrote a method for this. I just don't use it outside of zooming with wheel very often. Try the `zoomToPoint` method instead of the `focal` option and I *think* you'll get much closer to what you're expecting.

https://codepen.io/timmywil/pen/PoPvoYp
