### ISSUE TITLE
Feature: Multiple, Simultaneous, Side-by-Side Image Zoom for Comparison

### ISSUE THREAD

**Issue by HeyWrecker** [timmywil/panzoom#491]
Before submitting a feature request, please check [existing feature requests](https://github.com/timmywil/panzoom/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc) and add your :+1: reaction if your feature exists.

**What problem does this feature solve?**
Multiple Images, Side-by-Side, simultaneous zoom.

**Describe the solution you'd like**
When hovering over an image in a row of images being used for comparison, all should zoom to the same level.

**Describe alternatives you've considered**
jqZoom

**Additional context**
Here is a jsFiddle using jqZoom that illustrates what I'm trying to describe.

http://jsfiddle.net/h8jd5g93/

I did not see this implementation on the demo / example page and the use of an `id` seems to preclude "linking" or getting elements by class.

**Comment by timmywil** [comment]
Thanks for opening an issue. The old version of panzoom allowed for a jQuery set of elements on which to set the transform that I think would have solved this case. I took it out in the rewrite because I removed jQuery and kept it simple working with a single element at a time. That said, I think you could accomplish this behavior in the new version by using multiple Panzoom instances and setting the [`setTransform` option](https://github.com/timmywil/panzoom#settransform). Simply set whatever transform is passed on all of the elements.

That said, I'd be willing to add some equivalent of a `linked` option given more votes. Thanks.

**Comment by aerogt3** [comment]
This would be a really useful feature. Any hints or example of how to do this? Can't quite understand the setTransform option. Adding n-number of mousewheel zoom event listeners for each image sort of works, but the center of zoom is taken as the absolute coordinate of the image zoomed on. So the _amount_ of image zoom is synchronized, but the _zoom center_ is not.

**Comment by quentin-th** [comment]
> This would be a really useful feature. Any hints or example of how to do this? Can't quite understand the setTransform option. Adding n-number of mousewheel zoom event listeners for each image sort of works, but the center of zoom is taken as the absolute coordinate of the image zoomed on. So the _amount_ of image zoom is synchronized, but the _zoom center_ is not.

Hey, did you find a way to fix this, I think I have the same issue. 
Thanks
