### ISSUE TITLE
Scroll through horizontal image gallery where images are are panzoom objects.

### ISSUE THREAD

**Issue by Quasarman** [timmywil/panzoom#492]
Hello,

first thanks for this awesome library it works like a charm! I wanted to ask if it is possible to make it so panzoom does work when having the images with a panzoom instance within a horizontal scroll area? The problem I am facing is that the scrolling dosent work when trying to slide left/right on the image itself (the scrolling does work when not swiping on the image itself).Please see the gif I have attached to see the problem I am facing. 
![screenRecording](https://user-images.githubusercontent.com/30523269/85916549-1c4f2780-b852-11ea-8457-6fa8e5c0656d.gif)

Note: When removing the panzoom instance from the image I can scroll by sliding on the image itself, this is what I am trying to achieve. See below.

![screenRecording2](https://user-images.githubusercontent.com/30523269/85916595-a1d2d780-b852-11ea-8ad2-c5e54b531b01.gif)

So what I basically want is the panzoom functionality aswell as being abel to scroll the carousell by sliding left/right on the images. I tried it with the option *panOnlyWhenZoomed* aswell as slienting all events as stated in the docs, non of these options seem to work. Any advice would be welcome.

Thanks in advance.

**Comment by timmywil** [comment]
Thanks for opening an issue. Silencing events won't have an effect. `panOnlyWhenZoomed` is probably a good option to use, but it sounds like you also want `disablePan: true`. The reason it's not scrolling is that the panzoom start event calls 
 `preventDefault` and `stopPropagation`** on the pointer event by default. You can change this with the [handleStartEvent option](https://github.com/timmywil/panzoom#handlestartevent). While pinch zooming while scrolling might turn out weird, it should work okay. If you create a test case, I might be able to help further, but I think the existing options are enough to get this working.

**Comment by Quasarman** [comment]
Hello thanks for the response, Sadly none of the tips you gave me worked...both disabled the panning but still I was not able to scroll trough my carousel. Is there something else going on when swiping on a image with a panzoom instance on it? Anything else that gets blocked maybe? If I find the time I will create a codepen :)

Thanks for your help so far!

**Comment by timmywil** [comment]
Did you also try `handleStartEvent`? That one is essential as the event needs to make it to ancestor that is scrolling. In normal circumstances, the default is the desired behavior as the event can only be used for scrolling or for panning (not both), so `event.preventDefault()` and `event.stopPropagation()` is called. That's the reason why scroll wouldn't work. This is only necessary for the start event because the move and up handlers do not call those methods.

**Comment by Quasarman** [comment]
Yes I also tried the ```handleStartEvent``` with no effect.

**Comment by Quasarman** [comment]
I set it to a empty function like mentioned in the docs:
```
// Do nothing (this probably breaks things on mobile tho)
Panzoom(elem, {
  handleStartEvent: () => {}
})
```

**Comment by timmywil** [comment]
Ok, we can work through it more when you make an example.

**Comment by timmywil** [comment]
@Quasarman #494 was opened recently and I spun up the demo locally to play with this, and the solution was actually simple and I feel dumb for not remembering this before. The reason it won't scroll is due to styles set on both the panzoom element and panzoom parent element. Panzoom automatically did the following:

```ts
parent.style.touchAction = 'none'
elem.style.touchAction = 'none'
```

The native scroll interferes with panning and pinch zooming, which means both cannot work at the same time. However, I've added [an option](https://github.com/timmywil/panzoom#touchaction) to allow you to alternate touchAction values. This should be the tool you need to get the desired behavior.

While pinch zooming can't be enabled at the same time as scrolling, you could set the touchAction to `'none'` based on a long press or other gesture.

**Comment by Quasarman** [comment]
Hey @timmywil!

Thanks for the update and thanks for the addition. This really helps me a lot. Sorry for not providing an example myself I was really busy at work as well as with my masters degree.

Kind regards.
