### ISSUE TITLE
Feature: Visual Scroll Map

### ISSUE THREAD

**Issue by manuelgarciaph** [timmywil/panzoom#503]
**What problem does this feature solve?**
Provide users a whole view of the panzoom screen with a size that is larger than the viewport.

**Describe the solution you'd like**
Similar to the map used in gaming where you can see the whole game world, or the same with the scrolling feature of Sublime Text where the viewport is being highlighted as a fraction of the whole screen.

**Describe alternatives you've considered**
I tried using this library (https://github.com/demux/sublime-scroll/) but it only generated the visible viewport into an iframe. Plus, it only supports vertical scroll since it's designed to give an overall view of a webpage. In my case, I used panzoom to navigate my screen in all sorts of directions.
 
![1](https://user-images.githubusercontent.com/34462781/90765980-6cf87380-e31d-11ea-9e65-cd065e34bf63.png)
![12](https://user-images.githubusercontent.com/34462781/90766305-ea23e880-e31d-11ea-891e-db19605254a2.png)

**Comment by timmywil** [comment]
Thank you for opening an issue. I think you can implement this without adding code to Panzoom. In the two examples provided, you are seeing a re-rendering of a "Panzoom scene", not the Panzoom scene itself. In other words, take the game example. You are not seeing the actual map you are navigating in the minimap, but a small copy of it, probably stripped down for performance reasons. And your position is then *translated* to the minimap. All you'd need to implement this is a small copy of the whole scene and access to the x/y values and scale, all of which is already provided. I'm sorry I don't have time to write up an example for you, but what you need is there, and it would be all extra code (rather than code used in more than one place within the library) so I don't think it's a good fit for the library itself.
