### ISSUE TITLE
resizing causes image offset

### ISSUE THREAD

**Issue by micronaut** [timmywil/panzoom#508]
Hi,

I am trying to replace the jquery version of panzoom with the non-jquery version.  I have some functionality that toggles the size of the image container. With the old version I used to call reset and resetDimensions and the resizing/zoom/pan was handled properly.  Since that function is no longer available, the new version is not properly handling the resizing.  

I am using reset, but that is not working, the image is offset up and to the left inside the container.

Any ideas what may be causing this?

Thanks

**Comment by timmywil** [comment]
Thanks for opening an issue. The new version pulls the dimensions from the browser, rather than caching them. That's why `resetDimensions` no longer exists. It should be more accurate, but if dimension changes have not yet been painted, then the dimensions used would not be what you want. [Here's some more info about the async nature of Panzoom](https://github.com/timmywil/panzoom#a-note-on-the-async-nature-of-panzoom).

If that doesn't lead you in the right direction, please create a test case on jsbin.com or codepen.io and I can help debug.

Closing until we discover a change is needed in Panzoom.

Thanks.

**Comment by micronaut** [comment]
Thanks @timmywil
