### ISSUE TITLE
Pinching on mobile looks off on long images

### ISSUE THREAD

**Issue by rmatec** [timmywil/panzoom#513]
### Describe the bug

The pinching on mobile looks off when the image backing Panzoom is long. It appears as though the focal point is at the bottom of the image instead of being between the fingers.

### Your environment

- Version of panzoom -> 4.3.2
- Browser and browser version -> Safari 14 on iOS 14 / Chrome on Android 10

### Expected behavior

Pinching on mobile zooms in to the correct focal point (between the fingers)

### Actual behavior

Pinching on mobile zooms in to the wrong focal point.

### Steps to reproduce

Check this.
https://jsbin.com/qasezevicu/edit?html,js,output

**Comment by timmywil** [comment]
After some investigation, this is actually the same issue as #512. It will be fixed when I add the ability to center on the panzoom element rather than the viewport. You can confirm this by setting a height on the parent and centering the image vertically https://jsbin.com/nuyonijugu/1/edit?html,css,js,output
