### ISSUE TITLE
Replicating canvas-like behaviour

### ISSUE THREAD

**Issue by plc-dev** [timmywil/panzoom#525]
Hey, 
I'm trying to achieve similar behaviour to the second example of this canvas-lib:
http://fabricjs.com/fabric-intro-part-5 

Specifically this behaviour:
- Multiple panable objects in one "canvas"
- Zooming, while maintaining a scaled distance between the objects
- Dragging of the entire "canvas", with e.g. alt + drag
- Setting a initial layout of possibly nested objects

I've played around a bit with this library, but did not quite get the result I described above.

Could you maybe give me your assessment on wether you think this is doable with this library or if it is out of scope?

**Comment by timmywil** [comment]
Thanks for opening an issue. This should be doable with multiple instances of Panzoom on the objects as well as a wrapper instance of Panzoom. Without trying it myself, I can't say for sure. But the default behavior is close aside from the multiple draggable children.

**Comment by timmywil** [comment]
By the way, I think [this example](https://timmywil.com/panzoom/demo/#A%20Panzoom%20instance%20within%20another%20Panzoom%20instance) should be very close to what you're looking for. It has a panzoom instance within another. The zoom is controlled by the outer Panzoom. And more children could be added. In the case of clicking zoom buttons, I showed how to modify the children translations so that the child elements don't move when the parent is scaled.

**Comment by plc-dev** [comment]
Thanks for the fast response @timmywil 

The linked example was the first one I tried to build upon but didn't quite get to where I wanted.

Your suggestion of a wrapping Panzoom instance did the trick for me tho.

This is roughly what I ended up:

js
```
/* 
wrapper element acting as a canvas, to enable panning of the background
contain: outside to avoid panning out of boundaries
startCoordinates - (viewwidth|viewheight * (n-1)), where n is the vw/vh specified in the wrappers css to position it in the center
*/
const wrapper = panzoom(wrapper, {canvas: true, contain: "outside", startX: -window.outerWidth*2, startY: -window.outerHeight*2});
// attach zoom event listener to the wrapper element to keep relative positioning of child elements
root.addEventListener('wheel', (event: WheelEvent) => {
  wrapper.zoomWithWheel(event)
});

// create panzoom instance for every nested element
elements.forEach(element=> {
  panzoom(element);
});
```

html
```
<div class="root">
  <div class="wrapper">
      ...
      panzoom-elements
      ...
  </div>
</div>
```

css
```
.root {
  width: 100vw;
  height: 100vh;
}
.wrapper {
  width: 500vw;
  height: 500vh;
}
/*absolute styling, to avoid the need for nested flexbox elements */
.panZoomElements {
  position: absolute;
  ...
}
```

The only minor issue is, that the drag behaviour of the nested elements is a little finnicky, when zoomed out all the way, which is due to the contain-option I assume?

**Comment by timmywil** [comment]
Glad you got it working! I'm not sure about the nested elements. Doesn't look like you put contain on those. However, perhaps it's because the parent is scaled? If that's the case, the example linked above shows how you can override `setTransform` to divide the nested element transforms by the wrapper scale.
