### ISSUE TITLE
Incorrect zoomToPoint focal behavior (in Firefox)?

### ISSUE THREAD

**Issue by tmladek** [timmywil/panzoom#538]
### Describe the bug
When repeatedly calling `zoomToPoint()` with the `focal` option set to a single point, and just zooming back and forth, eventually, the view drifts away from the base point. (Losing some precision in the process?)

Additionally, while using `zoomWithWheel`, the view sometimes (every 10th step or so?) shifts unexpectedly up or down. 

### Your environment

- Version of panzoom: 4.3.2
- Browser and browser version: Firefox 84.0.2

This does not seem to happen on Chromium.

### Expected behavior

The `zoomToPoint` should not shift the position unexpectedly.

By no means I intend to boost "competition", but https://github.com/anvaka/panzoom seems to implement this behavior correctly.

### Actual behavior

When picking a point to zoom on, and rolling the scroll wheel, the focal point abruptly shifts 5-10px up or down in the process.

### Steps to reproduce

This happens even in the demos, or in the jsbin from #515, even with `animate: false`.

### Speculation

As mentioned, this does not seem to happen on Chromium - but both Firefox and Chromium do drift away when `animate: true` (as described in #515) - so I wonder if these behaviors may be related? (As far as I understand, the "ideal" case for focal zooming means the target point remains static, i.e. there's no reason why `animate: true` should slide the entire object away - unless there's some unintended pan drift happening.)

For example, if the bug wasn't just in Firefox, but if the `focal` calculation in `zoom()` was slightly wrong, it might simply not show up in Chromium as significantly as in Firefox due to, e.g. different rounding behavior in some positioning code.

Disclaimer: I haven't examined the code-base too deeply (except for trying to roll my own `zoomWithWheel()` and subsequently `zoomToPoint()`), so I may be completely off.

Thanks in advance!

**Comment by timmywil** [comment]
Thanks for opening an issue. I think this is just a matter of waiting for any changes to be completely painted before calling `zoomToPoint` again. One of the reasons Panzoom can stay small is that it leaves much of the calculation to the browser, as opposed to doing all the matrix calculations manually. The latter does help with the spamming issue, but the trade-off comes in maintenance and size. In other words, if an element is mid-move or mid-animate, the dimensions/transform used to calculate the next `zoomToPoint` may not be accurate yet. Make sense?

This is explained a bit more in the [README](https://github.com/timmywil/panzoom#a-note-on-the-async-nature-of-panzoom).

All things considered, I don't think it's the worth the change here. There are a couple ways to ensure the paint is done before allowing another call. You can use `setTimeout` in many cases, or bind to a `transitionend` event.

**Comment by tmladek** [comment]
>Make sense?

Not really! This also happens if I wait in between the scroll events. Hence why I do not think this is related to the async-ness of the behavior, as I mentioned.

**Comment by tmladek** [comment]
Consider this JS Bin for instance: https://jsbin.com/dedofawexe/edit

The focal point is the same for all `zoomToPoint()` calls, which happen with 1000ms delay *and* are queued via `setTimeout` - yet if you leave this running for some time, you will find that the view has drifted away.

**Comment by timmywil** [comment]
I did notice that when I tabbed out and came back to your example, the image changed position, but it's still the issue I described earlier. Browsers have an optimization where they will queue up the transform changes rather than do them in the background. When you come back, the changes all get played at once, and therefore won't paint the dimensions between each call. A `setTimeout` doesn't guarantee something is painted. I just pushes the call to the next JS loop. In many examples, this is enough to ensure the paint has happend, but not in yours. Perhaps the solution is to just turn off the timer when the tab loses focus.

**Comment by tmladek** [comment]
Unfortunately, the issue also manifests if you do *not* tab out. I suggest you try it!

(And once again, this makes me think that this is *not* related to async.)

**Comment by tmladek** [comment]
https://user-images.githubusercontent.com/5217341/104327303-e9693a00-54ea-11eb-929e-65208774d289.mp4

**Comment by timmywil** [comment]
Rest assured I have tried it. The only explanation I can think for the calculations being right sometimes and not others is because the calculation was done before a change was completely painted, which I am referring to as "async". I don't have to use that word here as your use case is different than the common one I was referring to in the README. While I tabbed out and came back to get the behavior you're describing, that's not necessarily the requirement there for what I was talking about to kick in. All that's really required is for the example iframe in jsbin to lose focus. This isn't normally an issue because you don't often have changes running on a `setInterval`.

What I'm suggesting is to try using the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) to conditionally disable changes to the Panzoom element.

**Comment by tmladek** [comment]
Ah, apologies; it sounded otherwise.

Although I am still not certain we understand each other - I would like to reiterate that it is not necessary for the tab to be out of focus for the bug to manifest. The video above was taken with the tab in focus.

Therefore, I do not think that Page Visibility API would anyhow help the issue; as page visibility is not a factor in either the jsbin example, or in the original issue.

**Comment by timmywil** [comment]
jsbin uses an iframe to render the example. I see in the video that you have the JS tab focused. That means the window in which Panzoom is being used does not have focus.

**Comment by tmladek** [comment]
Ah! That does make sense.

Nevertheless, here's a video of the same behavior in a separate (and of course, focused) document:



https://user-images.githubusercontent.com/5217341/104355392-e716d800-550a-11eb-8269-831af0be117a.mp4
