### ISSUE TITLE
Destroy method should reset changes

### ISSUE THREAD

**Issue by DanielStout5** [timmywil/panzoom#554]
Enabling Panzoom and then calling destroy() leaves a bunch of artifacts like `cursor:move` on the image, `overflow:hidden` on the parent, etc. Those changes should be undone after Panzoom is removed.

**Comment by timmywil** [comment]
While it is documented that `destroy` just removes the event listeners, I think I agree. I'll just make it remove styles as well, which will be simple enough.

**Comment by timmywil** [comment]
Ok, rather than changing the behavior of `destroy`, which would technically be a breaking change and warrant a major version release, I added a new method for resetting all of these styles.

```js
const panzoom = Panzoom(elem)
// ...
panzoom.destroy()
panzoom.resetStyle()
```

**Comment by timmywil** [comment]
This is now on the main branch. If you could try it out before I release, that would be very helpful.

```sh
$ git clone git@github.com:timmywil/panzoom.git
$ npm install
$ npm run build
```

See `/dist/panzoom.js`.

**Comment by timmywil** [comment]
I think this is generally how styles set by libraries are reverted. The value can then go back to whatever is set in CSS files or browser defaults. Note that getting computed styles can have side-effects like reflows, which can cause flashes. I could just check the style attribute, but saving all that is a good chunk of code. If you have a style you'd like it to be that isn't the browser default, just set it in your CSS file rather than in the style attribute.
