### ISSUE TITLE
Contain breaks initial rendering / unexpected 

### ISSUE THREAD

**Issue by Nashorn** [timmywil/panzoom#561]
These settings work. Starts at .5 scale, perfectly centered on x/y in viewport.
PROBLEM: 
User can pan the image out of view.
```
var panzoom = Panzoom(el,{
      startScale: .5,
      maxScale:   4,
      minScale:   .5,
      step:       .1
 });
```

When adding contain (any val) the image appears randomly top-right at .5 scale or top-left.
```
var panzoom = Panzoom(el,{
      startScale: .5,
      maxScale:   4,
      minScale:   .5,
      step:       .1,
      contain : "outside" //invert, automatic, true....none works
 });
```

**Comment by timmywil** [comment]
Thanks for opening an issue. To help debug, this issue needs a small test case from jsbin.com or codepen.io. Note the only valid values for `contain` in the non-jQuery version of the library are "inside" and "outside". As documented, `contain: 'outside'` only works if the panzoom element is larger than the parent and can take up all of the available space. Otherwise, you can get some unusual translations as Panzoom tries to make the element fit the parent.

Closing until there is a test case.
