### ISSUE TITLE
Question about getMatrix functionality

### ISSUE THREAD

**Issue by Madvatar** [timmywil/panzoom#568]
In earlier versions of PanZoom lib there was a function that could be used like this:
var transform = $('#svgcontainer').panzoom('getMatrix');

but that doesn't seem to exist in the latest version. I would have expected there to be a function like panzoom.getMatrix() to follow the rest of the API. Maybe there is some other function that I haven't found?

**Comment by timmywil** [comment]
Thanks for opening an issue. The `getMatrix` function no longer exists because the library no longer handles matrix calculations internally, instead passing that responsibility on to the browser. That said, all that function did before was get the computed transform and use regex to split it up. Panzoom does still have [`getPan`](https://github.com/timmywil/panzoom#getpan) and [`getScale`](https://github.com/timmywil/panzoom#getscale) to retrieve the cached x, y, and scale values, which should only differ from the real values in the browser mid-animation or pre-paint. Getting more than the scale or pan is now out of scope, but should be easy enough to retrieve without Panzoom: e.g. `window.getComputedStyle(elem).transform` will return the browser-calculated matrix in a string.
