### ISSUE TITLE
Panning after rotation showing blank space on edges

### ISSUE THREAD

**Issue by harshabikkavilli** [timmywil/panzoom#580]
### Describe the bug

Not sure if that is how its supposed to work or I am missing something.
When i have `contain: 'outside` set, I expect for the image not to pan past its edges. This is working as expected for an image without rotation. But after I rotate the image - applied rotation transform only on the image (child element), when I try to pan the image, I am seeing empty space.

[Sandbox link](https://codesandbox.io/s/imageview-with-panzoom-o36lj)

### Your environment

- Version of panzoom: 4.4.1
- Browser and browser version: Chrome (92.0.4515.131) 

### Expected behavior

When panning an image after rotation, should not pan past the edge and not show blank space.

### Actual behavior

When panning an image after rotation, able to pan past the edge and a blank space is showing up.

### Steps to reproduce

1. Load the image - unrotated
2. Rotate the image
3. Try zooming in to fill the parent element and then pan.
4. Observe that user is able to pan the image inside the parent element past its edges.

**Comment by timmywil** [comment]
Thanks for opening an issue. I don't currently have support for that. I'd have to think about the proper calculations, but it seems like a special case that would look weird for many cases. Depending on the ratio of the image and the size of the viewport, the image would have to be zoomed in to a level that basically made it unrecognizable. Plus, if Panzoom supported rotations in contain, it would probably need to support any kind of transformation including skew and any changes to the full 3d matrix. It's not impossible, but it would make for a much larger library. It gets even more complicated when you try to account for margin, padding, and border.

That said, this could be solved easily in many cases by adding a wrapper somewhere (probably as a parent) and applying the rotation to that instead of the panzoom element itself. That way the calculations on the Panzoom element can remain simple and the browser takes care of properly rotating. Everything Panzoom is doing could remain the same while the viewport itself is rotated. I would explore that and see if you can make it work before committing to doing the matrix calculations. I sort of have an example of this on the [demo page](https://timmywil.com/panzoom/demo/#Adding%20on%20matrix%20functions%20to%20the%20transform), but it applies the transform to the child image instead of to the parent element. See "Adding matrix functions to the transform" and then "Adding a transform to a child".
