### ISSUE TITLE
Scroll parent on element zoom and adjust element position in parent

### ISSUE THREAD

**Issue by jbingel** [timmywil/panzoom#601]
### Describe the bug

I have a fixed-position container `<div>` with `overflow: scroll` that holds a panzoomable element (say, an `<img>`). When zooming in on the `<img>` with focal point zooming (using the `.zoom(value)` method programmatically), the `<img>` is positioned at a negative `y` offset within the parent. 

So, to view the top part of the image, I now have to pan it down.

### Your environment

- Version of panzoom: 4.4.3 (using https://unpkg.com/@panzoom/panzoom@4.4.3/dist/panzoom.min.js)
- Browser and browser version: Chrome 95, Firefox 90

### Expected behavior

I would expect the image to always be aligned at the top of the parent container. On zooming, I would expect the scroll position of the parent to be set to the focal point of the image. After zooming, when scrolling all the way up on the parent, I would expect to see the top of the image.

### Actual behavior

On zooming, the zoomed image has a negative top position wrt. the parent. If I zoom when scrolled to the top of the container, the scroll position/scrollbar doesn't move and stays on top.

### Steps to reproduce

See this demo: https://jsbin.com/laruyubuxa/edit?html,output

**Comment by timmywil** [comment]
Thanks for opening an issue. However, panning and scrolling don't work well together as they are naturally in competition with each other. I would recommend supporting one or the other. But, that's not the real issue here. Essentially, scale transforms do not count as overflow natively, so even with no translation, you still would not be able to scroll the image into view when zoomed in. That's not something I can change in the library as it is native browser behavior. 

That said, there are ways to work around that behavior if you prefer scrolling to panning. Maybe this example will help: https://jsbin.com/bixakad/1/edit?html,js,output

This changes the `transform-origin` so the image stays in view in the scrolling area.
