### ISSUE TITLE
zoomIn function not focus to center of the screen

### ISSUE THREAD

**Issue by hongquan** [timmywil/panzoom#603]
### Describe the bug

Please look at the demo here: https://codepen.io/hongquan-vn/pen/bGoKyjg
When we click to ZoomIn, ZoomOut buttons, the hall is zoomed to the right bottom corner, instead of the center of the screen.

Not sure if it is a bug, or I didn't use Panzoom correctly, please help!

### Your environment

- Version of panzoom: 4.4.3
- Browser and browser version: Firefox v95.0.1 Linux

### Expected behavior

When clicking to ZoomIn, ZoomOut buttons, the hall should be zoomed at the center of the screen.

### Actual behavior

It is zoomed at the right bottom corner.

### Steps to reproduce

https://codepen.io/hongquan-vn/pen/bGoKyjg

**Comment by timmywil** [comment]
Thanks for opening an issue. It looks like your image is starting out with it's left at 0. zoomIn and zoomOut don't set translations by default. They rely on the native browser behavior. In this case, the `transform-origin` is already set to "50% 50%". In other words, it is zooming in and out on the center of the Panzoom element, but because the image is so large and because it's left is at zero, the center of the Panzoom element is down and to right. If re-orient the element to center from the start, you should start seeing zoomIn and zoomOut centered on the image. Hope that helps.

**Comment by hongquan** [comment]
@timmywil I think you misunderstood me. I don't mean to be center at the image, but the center of the screen. Like in this demo https://timmywil.com/panzoom/demo/, no matter where you put the image, the zoom is still centered at viewport.

Another way to understand the issue is that, in the https://codepen.io/hongquan-vn/pen/bGoKyjg, you scroll the mouse wheel until the image is smaller than the viewport, then you click the zoom buttons, you still see that the center of the zoom is somewhere very far to the right bottom, outside the image.

![image](https://user-images.githubusercontent.com/314607/148476628-7023c479-76ee-48e6-a605-eb7956b8a601.png)

**Comment by timmywil** [comment]
I understand, but I should have been more clear. The zoom doesn't happen towards the center of the image wherever it is. The zoom happens there because that's where the center of the image was at its original position and size. You can change that by starting the image centered, or you can zoom in on the point at the center of the viewport using the `zoomToPoint` method.
