### ISSUE TITLE
Error appears related to import error in @panzoom/panzoom/dist/src/panzoom.d.ts

### ISSUE THREAD

**Issue by LukeMapware** [timmywil/panzoom#615]
### Describe the bug

After clearing the node_modules and package_lock.json and running `npm install`, an error (shown below) appears, blocking launch of our application.

### Your environment

- Version of panzoom
Tested with 4.1.0 and 4.4.4
- Browser and browser version
Chrome 99.0.4844.84

### Expected behavior

Panzoom should not cause the application to fail building with either `ng build` or `ng serve`

### Actual behavior

The following error appears, preventing use of the application:
```
ERROR in node_modules/@panzoom/panzoom/dist/src/panzoom.d.ts:11:13 - error TS1005: '=' expected.

11 import type { PanzoomObject, PanzoomOptions } from './types';
               ~
node_modules/@panzoom/panzoom/dist/src/panzoom.d.ts:11:52 - error TS1005: ';' expected.

11 import type { PanzoomObject, PanzoomOptions } from './types';
```

### Steps to reproduce

Simply clear `node_modules` and `package_lock.json`, run `npm install`, and start a server to see the error.

**Comment by timmywil** [comment]
Thanks for opening an issue. I'm not sure your issue, but with all the demos and dev tests working, I can't reproduce your error. This kind of error might happen if you're using typescript but an old version, or importing types at an unusual step in the build process, or importing specific panzoom dist files directly in environments not meant for them rather than using `import Panzoom from '@panzoom/panzoom`. I can't say for sure, but whatever it is, I don't think changes are needed in Panzoom.

**Comment by LukeMapware** [comment]
No problem, I'll check my own environment, thank you!

**Comment by LukeMapware** [comment]
I want to mention, reverting to 4.0.0 appears to fix this issue.

**Comment by timmywil** [comment]
Interesting. If you can put together a small test case, I'll take a look! I started one for you here: https://codesandbox.io/s/weathered-field-d36pwl?file=%2Fsrc%2FApp.js

**Comment by LukeMapware** [comment]
I'll try it out if I have time, no idea what I did to get it to happen in the first place though! Thanks!
